language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"
install:
  - pip3 install --upgrade pip
  - pip install coveralls
script:
  - python test.py || python3 test.py
  - coverage run test.py
  - coverage report -m
after_success: coveralls
